/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arcade;
import Black_Main.Program;
import Black_View.BlackJack;
import TresRaya_Controlador.controlador;
import TresRaya_Modelo.juego;
import TresRaya_Vista.interfaz;
import ahorcado.ViewAhorcado;

import java.awt.Color;
import javax.swing.ImageIcon;
import mvc3nraya.Main;
import mvc_memory.principal;

/**
 *
 * @author Luis Trinidad
 */
public class Register1 extends javax.swing.JFrame {
    public boolean Go=false;

    /**
     * Creates new form View
     */
    public Register1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.BLACK);
        setTitle("MENU GAMES");
        setIconImage(new ImageIcon(getClass().getResource("/arcade/ICONO.png")).getImage());//icon for the aplication
    }

    public Register1(BlackJack aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConnectionButton = new javax.swing.JButton();
        ErrorDisplay = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConnectionButton1 = new javax.swing.JButton();
        ConnectionButton2 = new javax.swing.JButton();
        ConnectionButton3 = new javax.swing.JButton();
        ConnectionButton4 = new javax.swing.JButton();
        ConnectionButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ConnectionButton.setBackground(new java.awt.Color(255, 255, 255));
        ConnectionButton.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton.setForeground(new java.awt.Color(51, 51, 51));
        ConnectionButton.setText("M E M M O R Y");
        ConnectionButton.setToolTipText("");
        ConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButtonActionPerformed(evt);
            }
        });

        ErrorDisplay.setFont(new java.awt.Font("Onyx", 0, 24)); // NOI18N
        ErrorDisplay.setForeground(new java.awt.Color(255, 255, 255));
        ErrorDisplay.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .");

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("A R C A D E L A N D");

        ConnectionButton1.setBackground(new java.awt.Color(153, 153, 153));
        ConnectionButton1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton1.setForeground(new java.awt.Color(255, 255, 255));
        ConnectionButton1.setText("E X I T");
        ConnectionButton1.setToolTipText("");
        ConnectionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButton1ActionPerformed(evt);
            }
        });

        ConnectionButton2.setBackground(new java.awt.Color(0, 102, 255));
        ConnectionButton2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton2.setForeground(new java.awt.Color(255, 255, 255));
        ConnectionButton2.setText("T I C - T A C - T O E");
        ConnectionButton2.setToolTipText("");
        ConnectionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButton2ActionPerformed(evt);
            }
        });

        ConnectionButton3.setBackground(new java.awt.Color(0, 204, 0));
        ConnectionButton3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton3.setForeground(new java.awt.Color(255, 255, 255));
        ConnectionButton3.setText("B L A C K J A C K");
        ConnectionButton3.setToolTipText("");
        ConnectionButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButton3ActionPerformed(evt);
            }
        });

        ConnectionButton4.setBackground(new java.awt.Color(51, 51, 51));
        ConnectionButton4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton4.setForeground(new java.awt.Color(255, 255, 255));
        ConnectionButton4.setText("S T O N E / P A P E R / S C I S S O R S");
        ConnectionButton4.setToolTipText("");
        ConnectionButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButton4ActionPerformed(evt);
            }
        });

        ConnectionButton5.setBackground(new java.awt.Color(255, 153, 0));
        ConnectionButton5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        ConnectionButton5.setForeground(new java.awt.Color(255, 255, 255));
        ConnectionButton5.setText("H A N G M A N");
        ConnectionButton5.setToolTipText("");
        ConnectionButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectionButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("C L I C K    O N    A   G A M E   TO   P L A Y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ConnectionButton)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ConnectionButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ConnectionButton5)
                        .addGap(200, 200, 200))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(ConnectionButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ConnectionButton4)
                                    .addGap(11, 11, 11))
                                .addComponent(ErrorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConnectionButton2)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addComponent(ConnectionButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConnectionButton5)
                .addGap(11, 11, 11)
                .addComponent(ConnectionButton4)
                .addGap(11, 11, 11)
                .addComponent(ConnectionButton)
                .addGap(11, 11, 11)
                .addComponent(ConnectionButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(ConnectionButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButtonActionPerformed
    //MEMMORY
   principal view = new principal();
    view.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_ConnectionButtonActionPerformed

    private void ConnectionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectionButton1ActionPerformed

    private void ConnectionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButton2ActionPerformed
       //TIC TAC TOE
     juego modelo = new juego();
        interfaz vista = new interfaz();
        controlador controlador = new controlador( vista , modelo );
        controlador.iniciar_vista();
        vista.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ConnectionButton2ActionPerformed

    private void ConnectionButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButton3ActionPerformed
       //BLACKJACK
      
       BlackJack b = new BlackJack();
       b.setVisible(true);
       this.dispose();   
    }//GEN-LAST:event_ConnectionButton3ActionPerformed

    private void ConnectionButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButton4ActionPerformed
        // S T O N E / P A P E R / S C I S S O R S
        
    }//GEN-LAST:event_ConnectionButton4ActionPerformed

    private void ConnectionButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectionButton5ActionPerformed
//HANDMAN
ViewAhorcado v = new ViewAhorcado();
v.setVisible(true);
this.dispose();
      
    
        
    }//GEN-LAST:event_ConnectionButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectionButton;
    private javax.swing.JButton ConnectionButton1;
    private javax.swing.JButton ConnectionButton2;
    private javax.swing.JButton ConnectionButton3;
    private javax.swing.JButton ConnectionButton4;
    private javax.swing.JButton ConnectionButton5;
    private javax.swing.JLabel ErrorDisplay;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
