package TresRaya_Vista;

import Black_View.BlackJack;
import Conexion_DAO.Conexion;
import Conexion_Entidades.Persona;
import arcade.Register1;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 * @web www.jc-mouse.net/
 * @author Mouse
 */
public class interfaz extends javax.swing.JFrame {
       
    /** Creates new form vista */
    public interfaz() {
        initComponents();    
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.BLACK);
        setTitle("Tic-Tac-Toe");
        setIconImage(new ImageIcon(getClass().getResource("/TresRaya_image/tic-tac-toe.png")).getImage());//icon for the aplication
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        casilla1 = new javax.swing.JButton();
        casilla2 = new javax.swing.JButton();
        casilla3 = new javax.swing.JButton();
        casilla4 = new javax.swing.JButton();
        casilla5 = new javax.swing.JButton();
        casilla6 = new javax.swing.JButton();
        casilla7 = new javax.swing.JButton();
        casilla8 = new javax.swing.JButton();
        casilla9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        casilla1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla1.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla1);

        casilla2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla2.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla2);

        casilla3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla3.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla3);

        casilla4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla4.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla4);

        casilla5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla5.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla5);

        casilla6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla6.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla6);

        casilla7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla7.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla7);

        casilla8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla8.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla8);

        casilla9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        casilla9.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(casilla9);

        jMenu1.setText("File");

        jMenuItem1.setText("MENU");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Menu interfaz
        Register1 view = new Register1();
        view.setVisible(true);
        this.dispose();
        
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton casilla1;
    public javax.swing.JButton casilla2;
    public javax.swing.JButton casilla3;
    public javax.swing.JButton casilla4;
    public javax.swing.JButton casilla5;
    public javax.swing.JButton casilla6;
    public javax.swing.JButton casilla7;
    public javax.swing.JButton casilla8;
    public javax.swing.JButton casilla9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
